version: '3.8'

services:
  rules_matcher_app:
    image: rules_matcher:0.0.1
    container_name: rules_matcher_app
    depends_on:
      - rules_redis
    build:
      context: ./
    volumes:
      - ./:/app
    ports:
      - "7000:8001"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rules_redis:
    container_name: "rules_redis"
    image: redis:latest 
    ports:
      - 63791:6379
    restart: always
    
